name = "caminhodoperdao"
compatibility_date = "2024-11-01"
pages_build_output_dir = "build"

[env.production]
vars = { SITE_URL = "https://caminhodoperdao.pages.dev/" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "caminhodoperdao-db"
database_id = "784a0aec-8695-48d4-8ede-df680660735e"

[env.preview]
vars = { SITE_URL = "http://localhost:3000" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "caminhodoperdao-db"
database_id = "784a0aec-8695-48d4-8ede-df680660735e"
