name = "caminhodoperdao"
compatibility_date = "2024-11-01"
pages_build_output_dir = "build"

[env.production]
vars = { 
  SITE_URL = "https://caminhodoperdao.pages.dev/",
  REACT_APP_AMPLITUDE_KEY = "91645b6719db19112ae5de4f04319d1b",
  REACT_APP_AMPLITUDE_ENABLED = "true",
  REACT_APP_AMPLITUDE_SESSION_REPLAY = "false",
  REACT_APP_AMPLITUDE_DEBUG = "false"
}

[[env.production.d1_databases]]
binding = "DB"
database_name = "caminhodoperdao-db"
database_id = "784a0aec-8695-48d4-8ede-df680660735e"

[env.preview]
vars = { 
  SITE_URL = "http://localhost:3000",
  REACT_APP_AMPLITUDE_KEY = "91645b6719db19112ae5de4f04319d1b",
  REACT_APP_AMPLITUDE_ENABLED = "true",
  REACT_APP_AMPLITUDE_SESSION_REPLAY = "false",
  REACT_APP_AMPLITUDE_DEBUG = "false"
}

[[env.preview.d1_databases]]
binding = "DB"
database_name = "caminhodoperdao-db"
database_id = "784a0aec-8695-48d4-8ede-df680660735e"
